version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: "/myapp/docker-credentials/docker_username"
    DOCKER_REGISTRY_PASSWORD: "/myapp/docker-credentials/docker_password"
    DOCKER_REGISTRY_URL: "/myapp/docker-credentials/docker_registry_url"

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r <path-to-requirements.txt if any>
      
    
  build:
    commands:
       - cd <path-to-source-code>
       - echo "Building Docker Image"
       - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
       - docker build -t "docker.io/prathamdevops01/simple-python-flask-app:latest" . 
       - docker push "DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/simple-python-flask-app:latest"
       
  post_build:
    commands:
      - echo "Build is successful"
